spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
app:
  payment-secret-key: 8loMCgrU9E8TjNlrNElKwfGWdg6LrMxq